trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  GITHUB_NAME: 'Echizen Ryoma'
  GITHUB_EMAIL: 'echizenryoma.zhang@gmail.com'
  GIST_ID: '06bd306e9a1c0a26e8d81fe185ef77d0'

steps:
- powershell: |
    Write-Host '##vso[task.setvariable variable=CHOCOLATEY_API_KEY;issecret=true]secret'
    Write-Host '##vso[task.setvariable variable=GITHUB_API_KEY;issecret=true]secret'

    git config --global user.name "$(GITHUB_NAME)"
    git config --global user.email "$(GITHUB_EMAIL)"
    choco apikey --key "$(CHOCOLATEY_API_KEY)" --source 'https://push.chocolatey.org/'

    choco install -y au
  displayName: 'Get dependencies'

- powershell: |
    .\update_all.ps1
  displayName: 'Update Packages'
  workingDirectory: $(Build.SourcesDirectory)
  env:
    GITHUB_API_SEC_KEY: $(GITHUB_API_KEY)
